name: Build and test
on: push
jobs:
  sqlserver:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Start Docker for mssql-server
      run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=somepassword' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
  db2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
    - name: Make temporary directory
      run: mkdir -p ${{ env.workspace }}/tmp/database
    - name: Start Docker for ibmcom/db2
      run: docker run -itd --name mydb2 --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=password -e DBNAME=testdb -v ${{ env.workspace }}/tmp/database:/database ibmcom/db2
  mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
        - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
    steps:
    - uses: actions/checkout@v1
    - name: Connect
      run: mysql -h 127.0.0.1 --port 3306 -umysql -ppassword -e "SHOW DATABASES;"
  postgresql:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.4
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
        - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v1
    - name: Connect
      run: psql -h 127.0.0.1 -U postgres -d postgres -c "\l"
      env:
        PGPASSWORD: postgres
